image: alpine/3.11
packages:
  - bash
  - curl
  - zip
  - build-base
sources:
  - https://git.sr.ht/~ptek/kerestey.net
secrets:
- 413ecf62-8841-4720-ab61-bce2df38954a
tasks:
  - deploy: |
      cd kerestey.net
      set +xv
      source ~/.secrets/netlify
      set -x
      make deploy
triggers:
  - action: webhook
    condition: success
    url: "https://api.pushover.net/1/messages.json?user=u7kw3eiinpigo3mhtfn8vq136xr7o1&token=a1tf92orqeftc939putpw2w5jk9py4&message=kerestey.net%20deployed"
  - action: webhook
    condition: failure
    url: "https://api.pushover.net/1/messages.json?user=u7kw3eiinpigo3mhtfn8vq136xr7o1&token=a1tf92orqeftc939putpw2w5jk9py4&message=kerestey.net%20failed"